services:
  postgres:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/postgres:17
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  app:
    ports:
      - "127.0.0.1:3000:3000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  caddy:
    profiles: ["caddy"]
